### ISSUE TITLE
how add elasticsearch account name and password?

### ISSUE THREAD

**Issue by vitte70198147** [Programie/Telegram2Elastic#1]
hi! how can I correctly set my elasticsearch account name and password?

elasticsearch:
  host: http://localhost:9200
  **elasticsearch_username: telegram
  elasticsearch_password: password**
  index:
    # Specify the date format to use as the index suffix
    # "-" is automatically added between the prefix and the date
    # The following configuration will result in an index like "telegram-2020.03.18"
    # Without "date_format" the index will be named "telegram"
    date_format: "%Y.%m.%d"
    prefix: telegram

if you do so, then an error occurs:
`elasticsearch.AuthenticationException: AuthenticationException(401, 'security_exception', 'missing authentication credentials for REST request [/telegram-2022.09.24/_doc/13654]')`

if I specify the name and password in quotes, the error persists

**Comment by Programie** [comment]
You are almost right with the config you provided. Just remove the `elasticsearch_` prefix from the options.

Your Elasticsearch configuration in your config.yml should look like the following:
```yaml
elasticsearch:
  host: http://localhost:9200/
  username: telegram
  password: password
```

**Comment by Programie** [comment]
Seems like I've missed to add those options to the config.sample.yml when I've implemented the optional authentication. I've just added it to the sample file.
