### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by benborges** [Programie/Telegram2Elastic#4]
I'm throwing ideas here, feel free to punch me out if this is not in line of what you want to do : 

Each telegram message contains a text field, it's different for each type of message 
- pure text
- captions under single video posts
- captions under single image posts
- text under multi-image or multi-videos posts

What if we could specify Google or DeepL translation API in the config file and be able to store, both the original text inside Elastic Search, but also the translation (along with the media file or multi-media files)

what do you think ?

**Comment by Programie** [comment]
Thanks for coming up with those ideas! I'm always happy about feature requests for my projects.

Translating messages sounds useful (even if it's not useful for myself).

I will have a look in the Google Translator API as well as the DeepL API. I guess, they need an API key to access their API endpoints which will be required in the config file.

**Comment by Programie** [comment]
Maybe I could use [googletrans](https://py-googletrans.readthedocs.io/en/latest/) which works without providing an API key. But it might not be stable as Google might limit the amount of translation queries.

**Comment by benborges** [comment]
Yes that should work fine until a certain level but for having a python piece of code that does some that the limit is pretty high.

Having DeepL is more of a bonus, better quality translations in my experience.
(BTW DeepL also as a free tier api under more constrained limits)

**Comment by Programie** [comment]
OK, I will have a look in both, Google Translator as well as DeepL once I've finished #3.

**Comment by Programie** [comment]
If I understand it correctly, the Telegram API already provides a way to translate messages: https://core.telegram.org/api/translation

In that case, I don't have to add an additional dependency to Google Translator or DeepL. But I don't know whether that's already possible with Telethon. At least I couldn't find anything in the Telethon documentation.

**Comment by Programie** [comment]
As far as I can see, Telethon does not support the official [messages.translateText](https://core.telegram.org/method/messages.translateText) API method yet. So, I requested adding it to Telethon: https://github.com/LonamiWebs/Telethon/issues/4176

Once that feature has been added to Telethon, I can implement translating messages.

**Comment by Programie** [comment]
I've implemented translating messages using the translation API provided by Telegram.

You might test it. You just have to configure the target language using `translate_to_lang` (specify the two-letter ISO 639-1 language code).

Test translated message will be available in the `translated_text` which can then be mapped to any field using the output map configuration in the output config:

```yaml
outputs:
  - type: elasticsearch
    ...

    output_map:
      "message.original": "message.text"
      "message.translated": "translated_text"
```
